{{- if eq .Values.global.networkMode "gateway" }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: goldilocks-route
  namespace: goldilocks
spec:
  parentRefs:
    - name: nginx-gateway
      namespace: nginx-gateway
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - goldilocks.localhost
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: goldilocks-dashboard
          port: 80
          - group: ''	
            kind: Service
{{- end }}