apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-user
  namespace: rabbitmq
type: Opaque
stringData:
  username: admin
  password: admin
  default.conf: |
    default_user = admin
    default_pass = admin