apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-user-2
  namespace: rabbitmq
type: Opaque
stringData:
  connection_string: amqp://rabbitmq:rabbitmq@rabbitmqcluster-sample.rabbitmq.svc:5672/
  default_user.conf: |
    default_user = rabbitmq
    default_pass = rabbitmq
  host: rabbitmqcluster-sample.rabbitmq.svc
  password: rabbitmq
  port: "5672"
  provider: rabbitmq
  type: rabbitmq
  username: rabbitmq