argo-cd:
  configs:
    secret:
      createSecret: false
      # argocdServerAdminPassword: "$2a$10$9DMh/raHJuUHlycOhGe/Ze1rB7KXMDQuDScCfWMxHE7zS7IxsaCXy"
    params:
      server.insecure: true
  redisSecretInit:
    podAnnotations:
      sidecar.istio.io/inject: "false"