apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default                                # Reference to your AppProject
  destination:
    server: https://kubernetes.default.svc        # In-cluster Kubernetes API
    namespace: loki                         # Target namespace for the app
  
  sources:
    - repoURL: https://github.com/rdecuir/Local-Dev-Test-Cluster
      targetRevision: main
      ref: values

    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.31.0
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/apps/loki/values/values.yaml

  syncPolicy:
    automated:
      prune: true                                # Delete resources no longer defined
      selfHeal: true                             # Reapply if drift is detected
    syncOptions:
      - CreateNamespace=true