apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  admin.password: $2a$10$9DMh/raHJuUHlycOhGe/Ze1rB7KXMDQuDScCfWMxHE7zS7IxsaCXy
  admin.passwordMtime: "2025-06-12T00:00:00Z"
  server.secretKey: 1xMtuRC1KMZQXy2dz+Jho94dHHADNNaF84LQReMebtA=
# kubeseal --controller-namespace sealed-secrets --controller-name sealed-secrets --format yaml < ../example-secrets/argocd-login-secret.yaml > ../apps/secrets/SEALED-argocd-login-secret.yaml