apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
spec:
  project: default                                # Reference to your AppProject
  destination:
    server: https://kubernetes.default.svc        # In-cluster Kubernetes API
    namespace: rabbitmq-operator                           # Target namespace for the app
  
  sources:
    - repoURL: https://github.com/rdecuir/Local-Dev-Test-Cluster
      targetRevision: main
      ref: values

    - repoURL: https://charts.bitnami.com/bitnami
      chart: rabbitmq-cluster-operator
      targetRevision: 4.4.24
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/apps/rabbitmq-operator/values/values.yaml


  syncPolicy:
    automated:
      prune: true                                # Delete resources no longer defined
      selfHeal: true                             # Reapply if drift is detected
    syncOptions:
      - CreateNamespace=true