{{- $global_storage_class_name := .Values.storage_class_name -}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcap-claim
spec:
  storageClassName: {{ default $global_storage_class_name }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zeek-claim
spec:
  storageClassName: {{ default $global_storage_class_name }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suricata-claim-offline
spec:
  storageClassName: {{ default $global_storage_class_name }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-claim
spec:
  storageClassName: {{ default $global_storage_class_name .config_claim.classNameOverride }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runtime-logs-claim
spec:
  storageClassName: {{ default $global_storage_class_name }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi

{{- end }}