apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}-route
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: nginx-gateway
      namespace: nginx-gateway
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - {{ .Values.name }}.localhost
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.service }}
          port: 80
          group: ''
          kind: Service
          weight: 1