apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
spec:
  project: default                                # Reference to your AppProject
  destination:
    server: https://kubernetes.default.svc        # In-cluster Kubernetes API
    namespace: goldilocks                         # Target namespace for the app
  sources:
    - repoURL: https://github.com/rdecuir/Local-Dev-Test-Cluster
      targetRevision: main
      ref: values
      helm:
        valueFiles:
          - apps/helm-charts/goldilocks/values.yaml
        valuesObject:
          ingress:
            enabled: true
            path: /
            hosts:
              - goldilocks.localhost
            service:
              name: goldilocks-dashboard
              port: 80
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/router.entrypoints: web

    - repoURL: https://charts.fairwinds.com/stable
      chart: goldilocks
      targetRevision: 9.0.2

    - repoURL: https://charts.fairwinds.com/stable
      chart: vpa
      targetRevision: 4.5.*
  syncPolicy:
    automated:
      prune: true                                # Delete resources no longer defined
      selfHeal: true                             # Reapply if drift is detected
    syncOptions:
      - CreateNamespace=true     
