apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
spec:
  project: default                      # Reference to your AppProject
  sources:
    - repoURL: https://github.com/rdecuir/Local-Dev-Test-Cluster
      path: apps/helm-charts/goldilocks
      targetRevision: main
      ref: values
      helm:
        valueFiles:
          - values.yaml

    - repoURL: https://charts.fairwinds.com/stable
      chart: goldilocks
      targetRevision: 9.0.2

    - repoURL: https://charts.fairwinds.com/stable
      chart: vpa
      targetRevision: 4.5.*

  destination:
    server: https://kubernetes.default.svc        # In-cluster Kubernetes API
    namespace: goldilocks                         # Target namespace for the app
  syncPolicy:
    automated:
      prune: true                                # Delete resources no longer defined
      selfHeal: true                             # Reapply if drift is detected
    syncOptions:
      - CreateNamespace=true     