apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default                                # Reference to your AppProject
  destination:
    server: https://kubernetes.default.svc        # In-cluster Kubernetes API
    namespace: istio-system                             # Target namespace for the app
  
  sources:
  - repoURL: https://github.com/rdecuir/Local-Dev-Test-Cluster
    targetRevision: main
    path: apps/istio/manifests

  syncPolicy:
    automated:
      prune: true                                # Delete resources no longer defined
      selfHeal: true                             # Reapply if drift is detected
    syncOptions:
      - CreateNamespace=true
      # - ServerSideApply=true
      # - ApplyOutOfSyncOnly=true
      # - RespectIgnoreDifferences=true