apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default                       # Reference to your AppProject
  source:
    repoURL: https://github.com/rdecuir/Local-Dev-Test-Cluster.git
    targetRevision: main
    path: argo-apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc        # In-cluster Kubernetes API
    namespace: goldilocks                         # Target namespace for the app
  syncPolicy:
    automated:
      prune: true                                # Delete resources no longer defined
      selfHeal: true                             # Reapply if drift is detected
    syncOptions:
      - CreateNamespace=true     