apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/local-dev-test-cluster
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc        # In-cluster Kubernetes API
    namespace: argocd                           # Reference to your AppProject
  source:
    repoURL: https://github.com/rdecuir/Local-Dev-Test-Cluster
    targetRevision: main
    path: argo-apps
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true                                # Delete resources no longer defined
      selfHeal: true                             # Reapply if drift is detected  