apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
spec:
  project: default                                # Reference to your AppProject
  destination:
    server: https://kubernetes.default.svc        # In-cluster Kubernetes API
    namespace: sealed-secrets-contoller                     # Target namespace for the app
  
  sources:
    - repoURL: https://github.com/rdecuir/Local-Dev-Test-Cluster
      targetRevision: main
      ref: values
      path: apps/sealed-secrets-controller/templates # test this to allow templates in an app container folder
      
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.17.2
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/apps/sealed-secrets/values.yaml

  syncPolicy:
    automated:
      prune: true                                # Delete resources no longer defined
      selfHeal: true                             # Reapply if drift is detected
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true