apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default                                # Reference to your AppProject
  destination:
    server: https://kubernetes.default.svc        # In-cluster Kubernetes API
    namespace: argocd                             # Target namespace for the app
  
  sources:
  - repoURL: https://github.com/rdecuir/Local-Dev-Test-Cluster
    targetRevision: main
    path: apps/argocd/helm # test this to allow templates in an app container folder
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - ../values/values.yaml

  syncPolicy:
    automated:
      prune: true                                # Delete resources no longer defined
      selfHeal: true                             # Reapply if drift is detected
    syncOptions:
      - CreateNamespace=true
      # - ServerSideApply=true
      # - ApplyOutOfSyncOnly=true
      # - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data/admin.passwordMtime